apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # https://github.com/rancher/local-path-provisioner
  # https://github.com/rancher/local-path-provisioner/tree/v0.0.29/deploy
  - github.com/rancher/local-path-provisioner/deploy/?ref=v0.0.29


labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: local-path
